<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>{{ $itinerary->title }}</title>
    <style>
        body { font-family: Arial, sans-serif; }
        .header { text-align: center; margin-bottom: 30px; }
        .title { font-size: 24px; font-weight: bold; }
        .dates { color: #666; margin-top: 5px; }
        .destination { margin-bottom: 20px; border-bottom: 1px solid #ddd; padding-bottom: 15px; }
        .destination h3 { margin-bottom: 5px; }
        .time { color: #888; font-size: 14px; }
    </style>
</head>
<body>
    <div class="header">
        <div class="title">{{ $itinerary->title }}</div>
        <div class="dates">
            {{ $itinerary->start_date->format('F j, Y') }} - {{ $itinerary->end_date->format('F j, Y') }}
        </div>
        <p>{{ $itinerary->description }}</p>
    </div>

    <h2>Itinerary Schedule</h2>
    @foreach($itinerary->destinations as $dest)
        <div class="destination">
            <h3>{{ $dest->name }}</h3>
            <div class="time">
                Arrival: {{ $dest->arrival_time->format('M d, Y H:i') }} |
                Departure: {{ $dest->departure_time->format('M d, Y H:i') }}
            </div>
            <p>{{ $dest->description }}</p>
        </div>
    @endforeach

    <div style="margin-top: 30px; text-align: center; font-size: 12px; color: #999;">
        Generated by Travel Itinerary Planner on {{ now()->format('Y-m-d H:i') }}
    </div>
</body>
</html>
